import { PelanggaranRecord, SuratPeringatanRecord, PengeluaranSiswaRecord } from './types';

export const initialPelanggaranData: PelanggaranRecord[] = [
  {
    id: 'PLG-001',
    tanggal: '2026-09-18',
    siswaId: 'std-101',
    namaSiswa: 'Ahmad Fauzi',
    nisn: '0089281721',
    nisLokal: '202401001',
    kelas: 'X-A Ulya',
    jenisPelanggaran: 'Terlambat Shalat Berjamaah Subuh',
    kategori: 'Ringan',
    poin: 5,
    keterangan: 'Bangun kesiangan setelah piket malam asrama',
    lokasi: 'Masjid Utama Pesantren',
    tindakanPembinaan: 'Teguran lisan & tadarus Al-Qur\'an 1 juz',
    dicatatOleh: 'Ust. Hasan Basri (Bag. Keamanan)',
  },
  {
    id: 'PLG-002',
    tanggal: '2026-09-16',
    siswaId: 'std-102',
    namaSiswa: 'Muhammad Rizky Pratama',
    nisn: '0078192834',
    nisLokal: '202302045',
    kelas: 'XI-B Ulya',
    jenisPelanggaran: 'Membawa Smartphone Tanpa Izin Asrama',
    kategori: 'Sedang',
    poin: 20,
    keterangan: 'Ditemukan menyimpan HP di dalam loker kamar asrama saat sidak malam',
    lokasi: 'Asrama Putra Gedung Al-Fatih Lt. 2',
    tindakanPembinaan: 'Penyitaan HP selama 1 semester & pemanggilan wali',
    dicatatOleh: 'Ust. Salman Al-Farisi (Pembina Asrama)',
  },
  {
    id: 'PLG-003',
    tanggal: '2026-09-14',
    siswaId: 'std-103',
    namaSiswa: 'Dimas Ardiansyah',
    nisn: '0091827364',
    nisLokal: '202403012',
    kelas: 'IX-A Wustha',
    jenisPelanggaran: 'Keluar Area Pesantren Tanpa Izin (Mangkir)',
    kategori: 'Sedang',
    poin: 25,
    keterangan: 'Menerobos gerbang samping saat jam belajar mandiri',
    lokasi: 'Gerbang Samping Timur',
    tindakanPembinaan: 'Skorsing tidak boleh menerima kunjungan selama 1 bulan & hafalan surat Al-Mulk',
    dicatatOleh: 'Ust. Nurul Huda (Ketua Disiplin)',
  },
  {
    id: 'PLG-004',
    tanggal: '2026-09-11',
    siswaId: 'std-104',
    namaSiswa: 'Farhan Nur Hidayat',
    nisn: '0067281920',
    nisLokal: '202201089',
    kelas: 'XII-A Ulya',
    jenisPelanggaran: 'Perkelahian Fisik dengan Teman Sekamar',
    kategori: 'Berat',
    poin: 50,
    keterangan: 'Terlibat adu fisik yang mengakibatkan memar pada rekannya',
    lokasi: 'Kamar 04 Asrama Hamzah',
    tindakanPembinaan: 'Penerbitan Surat Peringatan II & isolasi pembinaan 7 hari',
    dicatatOleh: 'Ust. Zainal Abidin (Biro Pengasuhan)',
  },
  {
    id: 'PLG-005',
    tanggal: '2026-09-08',
    siswaId: 'std-105',
    namaSiswa: 'Rayhan Al-Ghifari',
    nisn: '0098273615',
    nisLokal: '202501033',
    kelas: 'VIII-C Wustha',
    jenisPelanggaran: 'Tidak Mengikuti Pengajian Halaqah Daimi',
    kategori: 'Ringan',
    poin: 10,
    keterangan: 'Tidur di kamar saat halaqah sore berlangsung tanpa surat izin sakit',
    lokasi: 'Gedung Madrasah R.201',
    tindakanPembinaan: 'Membersihkan selasar madrasah & mengulang setoran halaqah',
    dicatatOleh: 'Ust. Ridwan Kamil, Lc.',
  },
  {
    id: 'PLG-006',
    tanggal: '2026-09-05',
    siswaId: 'std-106',
    namaSiswa: 'Zaidan Malik',
    nisn: '0081726354',
    nisLokal: '202402019',
    kelas: 'X-B Ulya',
    jenisPelanggaran: 'Menghisap Rokok / Vape di Lingkungan Lembaga',
    kategori: 'Sedang',
    poin: 30,
    keterangan: 'Kedapatan merokok di area belakang kantin pesantren',
    lokasi: 'Area Belakang Kantin',
    tindakanPembinaan: 'Pemanggilan orang tua santri & penandatanganan surat pernyataan',
    dicatatOleh: 'Ust. Hasan Basri (Bag. Keamanan)',
  },
  {
    id: 'PLG-007',
    tanggal: '2026-08-29',
    siswaId: 'std-107',
    namaSiswa: 'Bagas Setiawan',
    nisn: '0109283746',
    nisLokal: '202501015',
    kelas: 'VII-A Wustha',
    jenisPelanggaran: 'Merusak Fasilitas Kamar Mandi Asrama',
    kategori: 'Sedang',
    poin: 15,
    keterangan: 'Merusak kran dan pintu kamar mandi karena bercanda berlebihan',
    lokasi: 'Kamar Mandi Asrama Abu Bakar',
    tindakanPembinaan: 'Ganti rugi perbaikan fasilitas & kerja bakti santri',
    dicatatOleh: 'Ust. Rudi Hermawan (Sarpras & Pengasuhan)',
  },
  {
    id: 'PLG-008',
    tanggal: '2026-08-20',
    siswaId: 'std-108',
    namaSiswa: 'Aditya Wijaya',
    nisn: '0076253412',
    nisLokal: '202301011',
    kelas: 'XI-A Ulya',
    jenisPelanggaran: 'Penyalahgunaan Akun Media Sosial & Pencemaran Nama Baik',
    kategori: 'Berat',
    poin: 75,
    keterangan: 'Membuat konten tidak pantas yang mencemarkan martabat asatidzah di media sosial',
    lokasi: 'Daring / Luar Area',
    tindakanPembinaan: 'Penerbitan Surat Peringatan III & Sidang Komite Disiplin',
    dicatatOleh: 'Biro Keamanan & Dewan Pertimbangan Pesantren',
  },
];

export const initialSuratPeringatanData: SuratPeringatanRecord[] = [
  {
    id: 'SP-001',
    tanggalTerbit: '2026-09-17',
    nomorSp: 'SP/01/KDS/YTS/IX/2026',
    siswaId: 'std-102',
    namaSiswa: 'Muhammad Rizky Pratama',
    nisLokal: '202302045',
    kelas: 'XI-B Ulya',
    tingkatSp: 'SP 1',
    status: 'Aktif',
    alasan: 'Akumulasi Poin Pelanggaran mencapai 35 Poin (Kepemilikan barang elektronik terlarang & ketidakhadiran ta\'lim)',
    berlakuHingga: '2026-12-17',
    poinAkumulasi: 35,
    tembusan: 'Wali Kelas XI-B, Mudir Pesantren, Orang Tua Santri',
  },
  {
    id: 'SP-002',
    tanggalTerbit: '2026-09-15',
    nomorSp: 'SP/02/KDS/YTS/IX/2026',
    siswaId: 'std-103',
    namaSiswa: 'Dimas Ardiansyah',
    nisLokal: '202403012',
    kelas: 'IX-A Wustha',
    tingkatSp: 'SP 2',
    status: 'Aktif',
    alasan: 'Pengulangan pelanggaran kabur dari asrama setelah sebelumnya diberikan teguran tertulis pertama',
    berlakuHingga: '2026-11-15',
    poinAkumulasi: 60,
    tembusan: 'Wali Santri, Kepala Madrasah Wustha, Biro Pengasuhan',
  },
  {
    id: 'SP-003',
    tanggalTerbit: '2026-09-12',
    nomorSp: 'SP/03/KDS/YTS/IX/2026',
    siswaId: 'std-104',
    namaSiswa: 'Farhan Nur Hidayat',
    nisLokal: '202201089',
    kelas: 'XII-A Ulya',
    tingkatSp: 'SP 2',
    status: 'Masa Pembinaan',
    alasan: 'Tindakan kekerasan fisik terhadap santri lain yang membahayakan keselamatan',
    berlakuHingga: '2026-10-12',
    poinAkumulasi: 65,
    tembusan: 'Dewan Guru, Mudir Pesantren, Wali Santri Bersangkutan',
  },
  {
    id: 'SP-004',
    tanggalTerbit: '2026-08-25',
    nomorSp: 'SP/04/KDS/YTS/VIII/2026',
    siswaId: 'std-108',
    namaSiswa: 'Aditya Wijaya',
    nisLokal: '202301011',
    kelas: 'XI-A Ulya',
    tingkatSp: 'SP 3',
    status: 'Sidang Disiplin',
    alasan: 'Akumulasi Poin Pelanggaran Melampaui Batas Toleransi (>95 Poin) & Pelanggaran Etika Berat',
    berlakuHingga: '2026-09-25',
    poinAkumulasi: 95,
    tembusan: "Pimpinan Yayasan, Mudir 'Am, Pengasuh Asrama, Wali Santri",
  },
  {
    id: 'SP-005',
    tanggalTerbit: '2026-07-30',
    nomorSp: 'SP/05/KDS/YTS/VII/2026',
    siswaId: 'std-109',
    namaSiswa: 'Kevin Santoso',
    nisLokal: '202401088',
    kelas: 'IX-B Wustha',
    tingkatSp: 'SP 1',
    status: 'Selesai',
    alasan: 'Ketidakhadiran shalat berjamaah lebih dari 10 kali dalam 1 bulan',
    berlakuHingga: '2026-08-30',
    poinAkumulasi: 25,
    tembusan: 'Wali Kelas IX-B, Wali Santri',
  },
];

export const initialPengeluaranData: PengeluaranSiswaRecord[] = [
  {
    id: 'DO-001',
    tanggalKeluar: '2026-09-02',
    siswaId: 'std-108',
    namaSiswa: 'Aditya Wijaya',
    nisLokal: '202301011',
    kelas: 'XI-A Ulya',
    alasanPemberhentian: 'Akumulasi Poin Pelanggaran Melampaui Batas Maksimal (>100 Poin) dan Mengabaikan Ketentuan SP 3',
    kategoriAlasan: 'Akumulasi Poin Maksimal',
    nomorSk: 'SK/PENGELUARAN/YTS/2026/012',
    tanggalSk: '2026-09-01',
    dokumenSkUrl: '/dokumen/sk/SK-DO-2026-012.pdf',
    ukuranDokumen: '320 KB',
    pejabatTtd: 'Dr. KH. Abdullah Syakir, M.Ag. (Pimpinan Lembaga)',
    keteranganTambahan: 'Telah diserahkan kembali secara resmi kepada orang tua kandung didampingi pihak Polsek setempat',
  },
  {
    id: 'DO-002',
    tanggalKeluar: '2026-08-15',
    siswaId: 'std-110',
    namaSiswa: 'Hendra Kusuma',
    nisLokal: '202402099',
    kelas: 'X-C Ulya',
    alasanPemberhentian: 'Mangkir dan Tidak Kembali ke Asrama Pesantren Lebih dari 45 Hari Kalender Tanpa Izin Resmi',
    kategoriAlasan: 'Mangkir / Kabur',
    nomorSk: 'SK/PENGELUARAN/YTS/2026/007',
    tanggalSk: '2026-08-14',
    dokumenSkUrl: '/dokumen/sk/SK-DO-2026-007.pdf',
    ukuranDokumen: '280 KB',
    pejabatTtd: 'Drs. H. Miftah Faridl (Mudir Bag. Pendidikan)',
    keteranganTambahan: 'Surat pemanggilan wali ke-1 hingga ke-3 tidak diindahkan oleh pihak keluarga',
  },
  {
    id: 'DO-003',
    tanggalKeluar: '2026-06-20',
    siswaId: 'std-111',
    namaSiswa: 'Ilham Ramadhan Pratama',
    nisLokal: '202401054',
    kelas: 'VIII-B Wustha',
    alasanPemberhentian: 'Pelanggaran Norma Berat dan Membawa Zat Berbahaya / Narkotika ke Lingkungan Pesantren',
    kategoriAlasan: 'Kriminal / Narkoba',
    nomorSk: 'SK/PENGELUARAN/YTS/2026/003',
    tanggalSk: '2026-06-19',
    dokumenSkUrl: '/dokumen/sk/SK-DO-2026-003.pdf',
    ukuranDokumen: '410 KB',
    pejabatTtd: 'KH. Mustofa Bisri (Ketua Dewan Syuro)',
    keteranganTambahan: 'Keputusan Sidang Pleno Asatidzah & Pengurus Yayasan, proses rehabilitasi dialihkan ke wali',
  },
];
